/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;
import java.util.*;

import sdp.prac2.SimpleFunctions;

public class App {
    public static void main(String[] args) {
        SimpleFunctions funcs = new SimpleFunctions();
    
    }
}
